### ISSUE TITLE
Example fails to compile with gcc 4.8.2

### ISSUE THREAD

**Issue by dersebi** [silentbicycle/greatest#10]
I am trying to compile with gcc 4.8.2 and the Makefile from git:

$ LANG=C make
cc -Wall -Werror -Wextra -pedantic -Wmissing-prototypes -Wstrict-prototypes -Wmissing-declarations   -c -o example-suite.o example-suite.c
example-suite.c:9:6: error: function declaration isn't a prototype [-Werror=strict-prototypes]
 TEST blah() {
      ^
cc1: all warnings being treated as errors
<builtin>: recipe for target 'example-suite.o' failed
make: **\* [example-suite.o] Error 1

This can be fixed by changing the offending line to
TEST blah(void) {
The same change has to be made at 8 other positions in example.c.

After that some more errors pop up:
$ LANG=C make
cc -o example example.c example-suite.o -Wall -Werror -Wextra -pedantic -Wmissing-prototypes -Wstrict-prototypes -Wmissing-declarations 
example.c: In function 'suite':
example.c:94:5: error: passing argument 1 of 'GREATEST_SET_SETUP_CB' from incompatible pointer type [-Werror]
     GREATEST_SET_SETUP_CB(trace_setup, NULL);
     ^
In file included from example.c:5:0:
greatest.h:180:6: note: expected 'void (_)(void *)' but argument is of type 'void (_)(void)'
 void GREATEST_SET_SETUP_CB(greatest_setup_cb _cb, void *udata);
      ^
example.c:95:5: error: passing argument 1 of 'GREATEST_SET_TEARDOWN_CB' from incompatible pointer type [-Werror]
     GREATEST_SET_TEARDOWN_CB(trace_teardown, NULL);
     ^
In file included from example.c:5:0:
greatest.h:181:6: note: expected 'void (_)(void _)' but argument is of type 'void (_)(void)'
 void GREATEST_SET_TEARDOWN_CB(greatest_teardown_cb _cb, void *udata);
      ^
cc1: all warnings being treated as errors
Makefile:12: recipe for target 'example' failed
make: *_\* [example] Error 1

This can be resolved by changing trace_setup() and trace_teardown() to require a void\* argument and using it.
